# Generated by Django 2.2 on 2020-10-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0002_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='sendemail',
            field=models.BooleanField(default=False),
        ),
    ]
