# Generated by Django 2.2 on 2020-10-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0003_schedules_sendemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='sendemail',
        ),
    ]
